name: Merge

on:
  schedule: 
  - cron: "0 0,2,4,6,8,10,12,14,16,18,20,22 * * *"
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest from spreadsheet
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch --unshallow
          git pull origin main
          pip install openpyxl
          python3 fetcher.py
          git add .
          git diff-index --quiet HEAD || git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
